[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "edgegraph"
requires-python = ">= 3.8"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/mishaturnbull/edgegraph"
Repository = "https://github.com/mishaturnbull/edgegraph"

