[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "edgegraph"
requires-python = ">= 3.8"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/mishaturnbull/edgegraph"
Repository = "https://github.com/mishaturnbull/edgegraph"

# Pylint settings
[tool.pylint.main]
# 0 = automatically detect # of cores for multiprocessing
jobs = 0

[tool.pylint."messages control"]
# messages that we don't care about.  justify each entry!
disable = [
            # improves readability in some IDEs
            "trailing-newlines",

            # "explicit is better than implicit"  - the zen of Python
            # why is this even a warning??
            "useless-object-inheritance",
           ]

