@startuml

class BaseObject<getsetattr> {
    Base class for all objects.
    __
    {field} +uid: int
    {field} +attributes: dict
    {field} +universes: Universe[]
    {method} +jsonify(): dict
    {method} +dejson(json)
}

@enduml
