@startuml

!include baseobj.iuml!0
!include vertices.iuml!0
!include links.iuml!0
!include mixins.iuml!0

BaseObject --|> Vertex
BaseObject --|> Link

Vertex --|> Universe
Universe ..> UniverseLaws
Universe --|> State 

Link --|> UndirectedEdge
UnDirectedEdge --|> DirectedEdge
DirectedEdge --|> Transition

SemiSingleton ..> Vertex
Conditional ..> Link

@enduml

