@startuml

class Link {
    Represents a link between
    multiple vertices.
    __
    {field} +vertices: Vertex[]
}

class DirectedEdge {
    v1 --> v2
    __
    {field} +v1: Vertex
    {field} +v2: Vertex
}

class UndirectedEdge {
    v1 -- v2
    __
    {field} +v1: Vertex
    {field} +v2: Vertex
}

class Transition {
    A transition between two States.
    __
    {field} +parameters: dict
    {method} +run()
}

@enduml

